version: '3.8'
services:
  tenpo-postgres:
    image: postgres:15
    container_name: tenpo_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calculation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tenpo-redis:
    image: redis:7.0
    container_name: tenpo_redis_container
    ports:
      - "6379:6379" # Puerto por defecto de Redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"] # Configuración básica
    volumes:
      - redis_data:/data

  tenpo-backend:
    #image: tenpo-backend-challenge:local
    image: codelious/tenpo-backend-challenge:latest  # Usando la imagen de Docker Hub
    container_name: tenpo_backend_container
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_R2DBC_URL: r2dbc:postgresql://tenpo-postgres:5432/calculation_db
      DATASOURCE_JDBC_URL: jdbc:postgresql://tenpo-postgres:5432/calculation_db
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: password
      REDIS_HOST: tenpo-redis
      REDIS_PORT: 6379
      PERCENTAGE_API_URL: https://42c939fb-7574-4341-91ca-b59c0ed06ddb.mock.pstmn.io
      PERCENTAGE_API_URI: /percentage
    depends_on:
      - tenpo-postgres
      - tenpo-redis

volumes:
  postgres_data:
  redis_data: